server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

weixin:
  config:
    originalid: gh_b5c3c9daf3bb
    token: weixin123
    app-id: wxbbaebcbec805657e
    app-secret: 21197da9601f02e110de0b13e6548fe5
    template_id: ZdzIU0iG9AEHwe856jYrdPPYd-Jcb7NAmdhN67EKus4

alipay:
  enabled: true
  app_id: 9021000162641161
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCx8mO+3M3716L/l0oU25tzQ3bUGoOVs4lC0GC89ViomPiGYVDneTiHshXwbqNbnAJGUsaNl3iux0JggKK9wrMhKkvx6iahPCjYIiK9b46DuG0HQr5q7K+aeSl08iFbwJn6g77k7x8wt5SILDW/OkTkD2K046vKnbWfzzCOuRGYq1bYKZzHnjDtErcVf8NmWE1DbZ5YAJ6bsMpU/qE6oatINeFFfyXeHNgyf2XMaptJpQmIfxHnQl+OnGgYvNt+5vEbJuzRHCJT81m9iDpQPoJVz10/vFxykT7yeV4PFPnRrXq3mtDIAN9m8I9ijO9O1oOAboGOvAkPuLT9BRvsnFDvAgMBAAECggEAL03ucjikkYR7klKXoP/YTUXr+uqpfExj+t0GOnVGgltYBfEs3rv86SXQa0AeMSZB/IvYuJ9Bt8TEwn6vxJ5TnEdwNPk4F7i0avB4J7/WNPH8GegGUspkzD3VZX9QmuGSjWQkhRuEQSEsXR7Tkuhck/v7E3dKnexa8gbUM7zDDsBbQAqCJUMbYWeI2hUTxRn4NVAZoxYh+J4kzxQX727gf8X/+DRr+eA13V8c61c2rvVaS4nVowPDQThWWQB5gWkxotssKdGCn3rT6SM/HJr59ONXylNnrTMKVA0G35dGdD98j55Ya/2ZxKwfXCgZr6GezmJxdTAO9nTAv+u/Q0ouUQKBgQDzCDND/gBCP/ekmm8JUmxPzdkZRoDs0fmNdQAMSg0zT5JB+ZbV3D++HjdDET/H8MxZQG0muzcQuwLPkHHZD4ug8myT/xrGpCN5FtWLUhFD7GCt3dgWbZtJ2ta6LLCSEvNN2hOd35SIqfcxAqplSgAZWH7xvM14mr3759Kz4OOs2wKBgQC7cSFeSVlFr9rTcuV/xOamzeMPcIscZaXCoby1Rg7fBp7depHwKxAnIjoN8nHEpoTL5K1sYRG159q57VE7eqGnJbBmFtZMTV6u9NLytI7kbWj5TGQzM7xzpqW94j46urs4qcMmabsLNOid792EHaa9nkNwFhcPFTUogz+GiRHefQKBgQC4hLtXnhvYMPT2toIjU78EgEealxr/sxSDwBc/PWH0WS+0g6lvyf9je1F9zDTeuwaLpQy6YV4Xh8VEjmjB4rmigyzI2OEdfDWqlBmh47dUGL32g/6yWJmUY2CwjYmp/lVYAIDwVnZRpKoXPezdZmfY1oXbR/vA28vu3D3vcImsDQKBgBbVwWrrJKUIt2/rH2phYngPvQm0fD4JZBhB++tZjZY+CDyTIhRQKreZw9jPIG0EnEj6ouYBLVcr18muz6afWfIy9Tp6rcC97DsEOG648G+DpLY6SDq0otC0DJ0FYu9ksEpG5C9Z0h+bYntbLXFa62VOUojlKAn+W2uEEckiCbtBAoGAKqTtCcFPJtbyycofRbBwfDsXWvTAC1G7z7UH4jIPHrXPZ2nbJCTlzva4ZGda7PWwlzPMeea9VAKga4vvaAxqjcutRKrDiZSpqYLrGhcTCKbhklPARr3ie5MeLxCNnlYks2wfu9MeY2297nc7hOGMK+oR3NsHZ+xzVPaiWrVgsX4=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhAV6O6esb4gaSJ7ySFM5ikYzYMErTydin5HnXODlFBYqpQNWohMMDVC0LIAb6Q/MpFKgE1p2XnG91+kNCF3QplzpREaxhejceU0ls9IRlYR+sEG3EeSj2Tl2wAHuzNhO4ujoJLbAs9Fa6RrgGZbxdw9AlaR9+J2L7cCfrEXqTnI2PveECAnEoT2gLXtLN/MsD8iPshI8vY1CUP4kFQXZiKTouVUUM9hQMfmq5WYhxIRCQLk8/Sr6AUxn+NYNfOEliqPI+hf4JOcg9Y558K0Bn1mGFQ9QYPQV7Rk0imrW+Y4TojtSPPreONn98wu9SE0gYpGmT8KIOyoSH8jmEM0S/QIDAQAB
  notify_url: https://147c4b08.r28.cpolar.top/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml



spring:
  datasource:
    username: root
    password: 142857
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  spring:
    data:
      redis:
        host: localhost
        port: 6379
        # 如果设了密码就加：password: 123456
        database: 0

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
